### PR TITLE
Feature/ghg emissions

### PR DESCRIPTION
**Pull request by agnessa**
Integrates the locations and historical emissions gems, which allows to run importers and use endpoints. Does not integrate data uploader for those datasets, because I ran out of time :)

```
rake db:migrate
rake locations:import
rake location_members:import
rake historical_emissions:import
```

Please note this is intended to be used with the new S3 bucket, which has relevant files prepared in the staging section (check your .env).

### CODE REVIEW

**Comment by simaob** [comment]
Should the `.env.sample` include the CW_FILES_PREFIX?

**Comment by agnessa** [comment]
> Should the `.env.sample` include the CW_FILES_PREFIX?

yes, good point, forgot to update it

**Comment by simaob** [comment]
I'm getting an error when running the tasks from a fresh install. See screenshots:
`rake db:migrate` works fine.

screen shot 2018-11-06 at 10 01 32
screen shot 2018-11-06 at 10 01 23

**Comment by simaob** [comment]
I think that maybe I was in the wrong branch :$

**Pull request merged**
