### PR TITLE
Feature/province module vulnerability adaptivity

### PR DESCRIPTION
**Pull request by tsubik**
I think this is ready for Code Review. I'm still waiting for details what to do with "Road Infrastructure" and "Health Facility" indicators, should I include them or not. So do not merge yet!

I didn't create RadarChart in cw-components as that would be more time consuming and time is the essence right now.

Data download and metadata modal is not done yet. Maybe a separate task for that? It's not done in most of the places. Should we download zip with data sources like on SA platform?

### CODE REVIEW

**Comment by tsubik** [comment]
Screenshot

"Sensitivity and exposure index" and "Adaptive capacity index" are taken from indicators data that's why they differ from the design.

image

**Comment by simaob** [comment]
On the metadata modal and download the answer is yes, should be same behaviour as in SA.

**Comment by tsubik** [comment]
Thanks for comments, all done :+1: 

I'm using a default recharts tooltip for this chart + simple styling to make it similar to other chart tooltips. If we want to display it differently we can customize it creating a new component.

Now, we have valid ACI and SEI indicators. One thing I'm not sure about is pre-computed SEI and ACI index values. Those provided values are little off compared to computing mean of underlying indicators (I used that method previously because I didn't notice SEI and ACI index value in the data file). I have to ask Aya about it. Maybe it wouldn't be easier to just always compute those indexes and not use the imported data for those 2 indicators.  Or maybe we are missing something.

Anyway, whatever will be decided we can merge this after code review and do the change to compute ACI and SEI in separate PR.

**Comment by simaob** [comment]
Nice =) Looking good for me. Just found a small style issue, see screenshot bellow, the title goes out of the tooltip box:

screenshot 2019-01-14 at 14 00 20

**Comment by tsubik** [comment]
Fixed! Thanks for spotting this @simaob

**Comment by simaob** [comment]
Perfect =)

**Pull request merged**
