### PR TITLE
Section contents are i18n from now on

### PR DESCRIPTION
**Pull request by tsubik**
Couple things here:

- single `localized` endpoint to get all translations `api/v1/translations` using the standard i18n rails way to store static content (and not only static)
- removing sections contents, that data is available in translations endpoint
- no need to run rake tasks to have sections content, just add a new key into an adequate file in `config/locale` directory
- translation fallback on the backend side. If there is no Indonesian translation it will return text in English
- a client can override the default text (the default one from the yaml file) in the admin tool -> translations page. That value is saved into the database and that is the first place when we look for the content. We may need to sync the database content into yaml files from time to time after the keys are translated to have better development experience.
- initial translation could be also done using other tools as there are plenty for i18n rails standard way
- we can filter the keys which client can override, not sure if we want to

image

API endpoint response
image

### CODE REVIEW

**Comment by tsubik** [comment]
Hmm, let me investigate this, because that is very weird behavior. Probably something with the fallbacks. So do you think we should show empty values if there is no translation? They need an easy way to find out which are not translated. 

I can add guidance. It will be easy to CAPITALIZE just the page name in the key, that could help too. Maybe even removing `app` prefix and I will rename the column key to something else to not confuse developers as that won't be the full key.

**Comment by simaob** [comment]
Yeah, maybe just showing it empty would make it easier to spot the ones that need translation. And on the guidance we can mention that there's a fallback to the english version when a translation is not available.

Good ideas on the keys! =) Thanks!

**Comment by tsubik** [comment]
Ok. Maybe boolean filter "empty only?" could be useful too, that is very easy to add.

**Comment by simaob** [comment]
Yes, definitely!

**Comment by simaob** [comment]
Thanks it is indeed! =)
But I found something else that maybe is not directly related with this PR: on the Historical Emissions Page there isn't any data displayed when I change the language to Indonesia.

**Comment by tsubik** [comment]
For English I don't have any data either. It does not work on the staging too.

**Comment by simaob** [comment]
There is not a lot of data but there is some, try changing province to Indonesia, or this URL: https://indonesia-platform-staging.vizzuality.com/en/national-context/historical-emissions?provinces=2%2C3%2C4%2C6%2C5%2C7%2C8%2C20%2C18%2C9%2C1

**Comment by tsubik** [comment]
Ok, then I will take a look. We have more data it is just not downloading the data for provinces, only for IDN. Maybe that would be quick fix.

**Comment by simaob** [comment]
OK, please do! =) if you can fix that, even better =D

**Comment by tsubik** [comment]
Province data should be downloaded now and it should work at least for English version. Getting Indonesian here to work is harder, need to dive deeper into that code. I will continue with this tomorrow.

**Comment by simaob** [comment]
Yes it's showing for english. =)

**Comment by tsubik** [comment]
I still have some issues with the data probably and I fixed couple more issues with filters. Sometimes clicking on "Top 10 emitters" stops working. Another open issue is that site crashes sometimes when changing the language, it works when you refresh the page. Emissions targets needs rethinking too.

**Comment by simaob** [comment]
Thank you, Tomasz! =) Looks good to me.

**Comment by tsubik** [comment]
I changed a few more things:
- Data translations for sector, metric, value categories names are imported into the `translations` table (the same where static content translations are stored). Using this way we don't have to re-import translations after importing new data for charts.
- GHG Emissions - I removed sector `Total` from all `absolute` metrics and also now the sum of sector's emissions is being shown on the chart (previously it was last sector emission). Now you will see the total emission of chosen sectors as the value.

**Comment by simaob** [comment]
Thanks for the latest changes, Tomek! =) They look good to me. Let's see if Marta has any thoughts when she's back, otherwise we can merge it. =)

**Comment by simaob** [comment]
@aabdaab another one for you to re-review. It looks fine to me. =) If you are happy with it we can merge this.

**Pull request merged**
