### PR TITLE
Fix/ghg metric changes

### PR DESCRIPTION
**Pull request by Bluesmile82**
This PR fixes some problems in the GHG chart. It branches from fix/ghg-top-10-emitters. The changes requested there will be fixed here to avoid more conflicts.

First unique commit is: Fix bug and warning 03b4e75

In this PR there are some fixes to the GHG chart:

- The partner provided precalculated data so the metric calculation is no longer needed.
- In GDP and per Capita options the sector option is locked to total and also target emissions are not shown.
- Unit is fixed and shown in the top of the chart.
- Top 10 emitters is fixed(https://github.com/ClimateWatch-Vizzuality/indonesia-platform/pull/23#issuecomment-441691443):
  - Fixed typos
  - The default selection is selecting the actual provinces now
  - You can see the provinces in the legend of the chart
  - The data is filtered correctly

image

### CODE REVIEW

**Comment by simaob** [comment]
still one conflict to solve here.

**Comment by Bluesmile82** [comment]
I added a common translation selector so we just have to add to the final selectors:

```
import { getTranslatedContent } from 'selectors/translation-selectors';

const requestedTranslations = [
  { slug: 'historical-emissions', key: 'title', label: 'title' }, ...
];

export const getSectionSelector = createStructuredSelector({
  ...
  translations: getTranslatedContent(requestedTranslations)
});

```

**Comment by aabdaab** [comment]
@Bluesmile82 it has the same problem with colors that I had in socioeconomics, you need to pass all y columns to the theme assigning function

**Comment by Bluesmile82** [comment]
Yes, I think I'll fix that after finishing the CW GHG emissions. I want to pick a function from there

**Pull request merged**
