### PR TITLE
Add energy section to socioeconomics

### PR DESCRIPTION
**Pull request by aabdaab**
This PR wraps up socioeconomics page by adding Energy section:

image

### CODE REVIEW

**Comment by Bluesmile82** [comment]
The unit is wrong in this case. It should have no unit or % as it is a percentage. Also we might display it in a percentage type chart

**Comment by aabdaab** [comment]
right, I was confused by the design; in the API it is `%`

**Comment by aabdaab** [comment]
@simaob I think you're right: `elec_ratio` and `ins_power` are in the indicators of socioeconomics as well, I'm guessing these are the missing ones?

**Comment by aabdaab** [comment]
^ I added missing indicators for energy and fixed the issue with re-assigning colours when modifying the legend. I also fixed the units; they all come from the API now.

**Pull request merged**
