### PR TITLE
Feature/indicators

### PR DESCRIPTION
**Pull request by tsubik**
Endpoint to return indicators with values `api/v1/indicators`

We can filter values by `location` or indicator `section`

available sections:
`socioeconomic` - socioecomomic indicators
`adaptation` - adapatation indicators
`province_circumstances` - Energy, Forestry, Agriculture data

```
{
  "values": [
    {
      "indicator_code": "pop_total",
      "location": "Indonesia",
      "location_iso_code3": "IDN",
      "category": null,
      "values": [
        { "year": "2010", "value": 238.0 },
        { "year": "2011", "value": 242.0 },
        { "year": "2012", "value": 245.0 },
        { "year": "2013", "value": 248.0 },
        { "year": "2014", "value": 252.0 },
        { "year": "2015", "value": 255.0 },
        { "year": "2016", "value": 258.0 },
        { "year": "2017", "value": null }
      ]
    }
  ],
  "indicators": [
    { "section": "socioeconomic", "code": "pop_total", "name": "Population", "unit": "thousand" },
    { "section": "socioeconomic", "code": "pop_growth", "name": "Population growth", "unit": "%" }
  ]
}

```

```
bundle exec rake db:migrate
bundle exec rake db:admin_boilerplate:create
bundle exec rake db:import
```

Tackling all indicators stories:
- https://www.pivotaltracker.com/story/show/161648777
- https://www.pivotaltracker.com/story/show/161651153
- https://www.pivotaltracker.com/story/show/161675303
- https://www.pivotaltracker.com/story/show/161651049

### CODE REVIEW

**Comment by simaob** [comment]
Hi @tsubik I was downloading the CSV and am wondering if we should "explode" the years into columns, instead of serving as an hash on the last column. What do you think?

**Comment by tsubik** [comment]
Right @simaob that would be a better idea for csv.

**Comment by tsubik** [comment]
Ok, done, the only thing is that for some indicators we have year ranges instead of single years, and if we download values for those indicators we end up with columns like "2009_2010", but maybe that's not a problem.

**Comment by tsubik** [comment]
ahh wait, I forgot about "source" for values. I will update existing migration, so please redo them.

**Pull request merged**
