### PR TITLE
Feature/historical emissions

### PR DESCRIPTION
**Pull request by Bluesmile82**
This PR adds the historical emissions chart. Should work also for the redesign of CW GHG emissions. Still a bit of refactor is need to be made.

Notes: 
- Top 10 provinces option still needs to be added
- Data is very limited and CAIT doesn't have data,the option is just to be able to see the switch
- Info button is missing the source yet

image

### CODE REVIEW

**Comment by weberjavi** [comment]
Just a quick comment regarding design.
Maybe we have to set up a maximum height for the tooltip?

image

**Comment by simaob** [comment]
if Marta approves it, then feel free to merge! I'll redeploy later =) I must leave for a bit now

**Comment by aabdaab** [comment]
hmm something's not right when I direct to historical emissions:

image

The legend is there but there's no content.
Also the buttons are different from the design:

image

And we definitely have to do sth with that tooltip... The list is so long that we can't see the bottom of it

**Comment by Bluesmile82** [comment]
Buttons ready!

**Pull request merged**
