### PR TITLE
Fix/climate funding table fun

### PR DESCRIPTION
**Pull request by weberjavi**
This PR forces width of `website_link` column to avoid undesired overflow on the table.
[Pivotal](https://www.pivotaltracker.com/story/show/163790391)

This `cw-components` [PR](https://github.com/ClimateWatch-Vizzuality/climate-watch-components/pull/127) should be released and components version updated in this branch before this PR is ready to be reviewed.

### CODE REVIEW

**Comment by weberjavi** [comment]
Ready to review ☝️

**Comment by kfilip94** [comment]
@weberjavi Looks good to me!
When we will be doing a responsive version of this view, we will have to add a horizontal scroll anyway, because for smaller resolutions columns may be clipped. Do you think it would be difficult to do it in this PR?

**Comment by weberjavi** [comment]
Some changes should be made to this function:
https://github.com/ClimateWatch-Vizzuality/climate-watch-components/blob/master/src/components/table/table.js#L75
to allow `shouldOverflow` property to work as intended as setColumnWidth is not properly used (it consumes a `column` param).
We could make a PR to components repo fixing this and apply it on Indonesia platform upgrading `cw-components` repo.
Opened a Pivotal task here:
https://www.pivotaltracker.com/story/show/164608225

**Comment by simaob** [comment]
Sorry to be annoying :P but let's do it if it's a simple thing :D

**Comment by simaob** [comment]
since Javi just left, let's do it later.

**Pull request merged**
