### PR TITLE
Feature/metadata modals

### PR DESCRIPTION
**Pull request by tsubik**
All metadata popups. My initial estimation was very optimistic :]. There were a lot of missing bits and pieces here (info buttons, translations, refactoring needed in few places).

Beside of adding popups I'm also:
- removed `package-lock.json` file and add `.npmrc` config to not ever create this file
- specified node version to `8`
- added missing `recharts` and `react-motion` to package.json. I had errors of missing packages when I was trying to test cw-components locally (I failed to test the lib locally but didn't have time to dive into other errors)

image

### CODE REVIEW

**Comment by simaob** [comment]
Looks great =) Just one remark, it seems that the livestock and area of rice harvested has the wrong source associated with it, on this page: http://localhost:3000/en/regions/ID.AC/sectoral-circumstances

Is this an issue with their source data, or our importing?

**Comment by tsubik** [comment]
That is the data, for Agriculture, we have STATIDNc and STATIDNd associated. If this is wrong then the data must be corrected and reimported. I see that Energy is also wrong but here I just need to upload a new corrected file and reimport.

**Comment by simaob** [comment]
let me re-import, I was seeing it swapped.

**Comment by simaob** [comment]
Not sure why I was seeing a mismatch. Re-imported it all and looks good now!

**Pull request merged**
