### PR TITLE
Add carousel to home component

### PR DESCRIPTION
**Pull request by weberjavi**
This PR adds a `Carousel` to the home page.
[Designs](https://projects.invisionapp.com/share/TVOT4IFXDQ2#/screens/328013261)
[Pivotal task](https://www.pivotaltracker.com/story/show/161727926)

kapture 2018-11-14 at 9 26 39

__Note__:
Another iteration on the `Carousel` behaviour should be  done due to further design decisions.
The improvements to implement are described in [this Pivotal task](https://www.pivotaltracker.com/story/show/161948559)
On this second iteration final content should be displayed on the slides.

### CODE REVIEW

**Comment by aabdaab** [comment]
@weberjavi I updated cw-components so you can address what has changed in here ☝️

**Comment by weberjavi** [comment]
@aabdaab, @Bluesmile82 new version of the `Carousel` ☝️ 
Definitive content is yet to be defined so placeholder texts and images are displayed.

kapture 2018-11-15 at 12 56 14

**Comment by Bluesmile82** [comment]
Something seems wrong with the selection menu. Maybe I'm missing an import
image

Also, could we add some padding to the links so that we don't have to click exactly the text to make them work? Top and bottom I mean.

**Comment by weberjavi** [comment]
@Bluesmile82 ready to review ☝️ 
Thanks for the clicking issue catch 🐛 ⚔️

**Pull request merged**
